version: '3'
services:
  whatsapp_platform:
    container_name: test_whatsapp_platform
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50337:8000"
    restart: unless-stopped
    env_file:
      - .env
